### ISSUE TITLE
The sample is dont work in win 10 VS 2015 with all installed sdk

### ISSUE THREAD

**Issue by kolenchits86** [ExtCore/ExtCore-Sample#6]
![image](https://cloud.githubusercontent.com/assets/3372696/22751021/b800a288-ee54-11e6-85ed-a8f73c98f105.png)

**Comment by DmitrySikorsky** [comment]
Hi! Thank you for the screenshot, it makes it easy to find the reason of the problem. You need to install the SDK of that version. As I remember, it is sdk for .net core 1.1. I can try to find the link for you if you have problem with finding it. The sample is 100% working, the issue is only in the version.

**Comment by kolenchits86** [comment]
i download a latest sdk kit from https://www.microsoft.com/net/core#windowsvs2015 and dont error still there

**Comment by DmitrySikorsky** [comment]
Please check the following path: C:\Program Files\dotnet\sdk
Here you can see the list of the installed SDK versions. That is what I have for example:
![screen](https://cloud.githubusercontent.com/assets/6570196/22757818/fa28453a-ee54-11e6-9ea0-9ce3086ebe2e.png)

**Comment by DmitrySikorsky** [comment]
I think you need to install the specified version OR you can try just to change the SDK version to the never one you have installed.
